### ISSUE TITLE
无法install

### ISSUE THREAD

**Issue by lCATl** [licailing/arco-vue-pro-components#2]
npm install --save @acro-vue-pro-components/pro-components 无法安装呢

**Comment by sakurasuki** [comment]
大佬没发这个包 直接拖项目里用吧

**Comment by sakurasuki** [comment]
> npm install --save @acro-vue-pro-components/pro-components 无法安装呢
大佬没发这个包 直接拖项目里用吧

**Comment by licailing** [comment]
用pnpm安装吧
npm install -g pnpm
pnpm install @arco-vue-pro-components/pro-components

**Comment by lCATl** [comment]
> 用pnpm安装吧 npm install -g pnpm pnpm install @arco-vue-pro-components/pro-components

我试一下
